language: python
python: "2.7"

env:
    global:
        - PTERO_PETRI_HOME=ptero-petri
        - PTERO_FORK_HOME=ptero-shell-command-fork

install: pip install tox

before_script:
    - git clone --depth 1 https://github.com/mark-burnett/ptero-petri.git
    - git clone --depth 1 https://github.com/mark-burnett/ptero-shell-command-fork.git

script:
    - tox

after_success:
    - pip install coveralls
    - coveralls
