language: python
python: "2.7"

addons:
    postgresql: "9.3"

install: pip install tox==1.9.0

before_script:
    - sudo update-alternatives --install /bin/sh sh /bin/bash 100
    - sudo rabbitmq-plugins disable rabbitmq_management
    - git clone --depth 1 https://github.com/genome/ptero-petri.git
    - git clone --depth 1 https://github.com/genome/ptero-shell-command.git
    - psql -c 'create database ptero_workflow;' -U postgres

env:
    global:
        - PTERO_WORKFLOW_TEST_STARTUP_WAIT=15
        - PTERO_SHELL_COMMAND_HOME=./ptero-shell-command
        - PTERO_PETRI_HOME=./ptero-petri
        - PTERO_WORKFLOW_DB_STRING=postgres://postgres@localhost/ptero_workflow
        - TRAVIS_WAIT_TIME=120

script:
    - tox -e py27

after_success:
    - pip install coveralls
    - coveralls

after_failure:
    - for i in $(ls var/log/fail); do echo '=======${i}======='; cat $i; done
