language: python
python: "2.7"

install: pip install tox

before_script:
    - sudo rabbitmq-plugins disable rabbitmq_management
    - git clone --depth 1 https://github.com/genome/ptero-petri.git
    - git clone --depth 1 https://github.com/genome/ptero-shell-command.git

script:
    - tox

after_success:
    - pip install coveralls
    - coveralls

after_script:
    - ps -efl > var/log/ps.out
    - bash -c 'for f in var/log/*; do echo; echo "============================================"; echo $f; echo "============================================"; cat $f; done'
