language: python
python: "2.7"

addons:
    postgresql: "9.3"

install: pip install tox==2.1.1

before_script:
    - sudo update-alternatives --install /bin/sh sh /bin/bash 100
    - sudo rabbitmq-plugins disable rabbitmq_management
    - sudo psql -c 'create database ptero_workflow;' -U postgres
    - sudo psql -c 'create database ptero_shell_command;' -U postgres
    - git clone --depth 1 https://github.com/genome/ptero-petri.git
    - git clone --depth 1 https://github.com/genome/ptero-shell-command.git

env:
    global:
        - PTERO_SHELL_COMMAND_HOME=./ptero-shell-command
        - PTERO_PETRI_HOME=./ptero-petri

script:
    - tox

after_success:
    - pip install coveralls
    - coveralls

after_failure:
    - bash -c 'for f in var/log/fail/*; do echo; echo "============================================"; echo $f; echo "============================================"; cat $f; done'
